# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEWalletflip():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_eWalletflip(self):
    self.driver.get("https://basic.amanah-staging.cs.ui.ac.id/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.LINK_TEXT, "Donasi").click()
    self.driver.find_element(By.CSS_SELECTOR, ".aspect-\\[4\\/3\\]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a > .btn-outline").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "a > .btn-outline")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "paymentMethod").click()
    dropdown = self.driver.find_element(By.NAME, "paymentMethod")
    dropdown.find_element(By.XPATH, "//option[. = 'E-Wallet']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card-actions > .btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".card-actions > .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "name").click()
    self.driver.find_element(By.NAME, "name").send_keys("selenium user")
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("try@gmail.com")
    self.driver.find_element(By.NAME, "phone").click()
    self.driver.find_element(By.NAME, "phone").send_keys("089517313209")
    self.driver.find_element(By.NAME, "amount").click()
    self.driver.find_element(By.NAME, "amount").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(5) > .input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(5) > .input").send_keys("donasi selenium")
    self.driver.find_element(By.NAME, "ewallet_type").click()
    self.driver.find_element(By.NAME, "ewallet_type").send_keys("qris")
    self.driver.find_element(By.NAME, "vendor_name").click()
    dropdown = self.driver.find_element(By.NAME, "vendor_name")
    dropdown.find_element(By.XPATH, "//option[. = 'Flip']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card-actions > .btn").click()
    
    # Check detail
    time.sleep(2)  # Adding delay
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .btn").click()
    time.sleep(2)  # Adding delay
    
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".mb-2:nth-child(13) > div")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".mb-2:nth-child(12) > div")
    assert len(elements) > 0
  
