# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException

def is_logged_in(driver):
    try:
        driver.find_element(By.XPATH, "//button[contains(@class, 'btn-ghost') and contains(text(), 'Keluar')]")
        return True
    except NoSuchElementException:
        return False
    
def perform_login(driver):
    driver.find_element(By.CSS_SELECTOR, ".hover\\3Atext-base-primary").click()
    driver.find_element(By.NAME, "email").click()
    driver.find_element(By.NAME, "email").send_keys("admin@user.com")
    driver.find_element(By.NAME, "password").click()
    driver.find_element(By.NAME, "password").send_keys("123456")
    driver.find_element(By.CSS_SELECTOR, ".h-full").click()
    driver.find_element(By.XPATH,"//button[text()='Masuk']").click()
    